import {exercises} from './exercises.mjs';
const topic = id => `https://learn.inside.dtu.dk/d2l/le/content/326408/viewContent/${id}/View`;
const unit = id => `https://learn.inside.dtu.dk/d2l/le/lessons/326408/units/${id}`;
export const course = {
  id: '12106', title: 'Quantitative Sustainability', term: 'Fall 2026', case: 'Microfabrication', verified: '8 October 2026',
  learn: unit(1250709), caseUrl: unit(1250735), caseBrief: topic(1251169), schedule: topic(1250772), deadlineSource: topic(1250726),
  catalogue: 'https://kurser.dtu.dk/print/courses', examSource: 'https://student.dtu.dk/en/exam/exam-dates',
  breakStart: '2026-10-12', breakEnd: '2026-10-18',
};
const contribution = 'Include a Table of Contributions agreed by every group member.';
const declaration = 'Declare any use of language models. No specific document format is required.';
export const obligations = [
  {id:'enrol',title:'Join your case-study group',audience:'Individual',due:'2026-09-11T23:59:00+02:00',date:'11 September',time:'23:59',url:unit(1250719),source:course.deadlineSource,checklist:['Confirm enrolment in your chosen case and group in DTU Learn.'],description:'Group and case enrolment.'},
  {id:'task1',title:'Task 1 · Problem formulation',audience:'Group',due:'2026-09-30T23:59:00+02:00',date:'30 September',time:'23:59',url:topic(1251172),source:topic(1251000),description:'Define what you are assessing, why, and within which boundaries.',checklist:['Introduce your microfabrication topic, context and motivation across environment, economy and society.','State the purpose and scope; define the object of assessment and a quantified functional unit.','Set system boundaries and explain assumptions.','One person submits for the whole group in FeedbackFruits.',contribution,'Default maximum: 7,200 characters (about 3 pages), excluding bibliography and tables; case-specific instructions take precedence.',declaration]},
  {id:'peer1',title:'Task 1 · Give peer feedback',audience:'Individual',due:'2026-10-07T23:59:00+02:00',date:'7 October',time:'23:59',url:topic(1251172),source:topic(1250999),description:'Each student reviews two other groups. A group submission does not complete this obligation.',checklist:['Review both assigned group submissions individually in FeedbackFruits.','Address every assessment criterion for both submissions.','AI use in peer feedback is not allowed.','As a group, consider received feedback for revisions.']},
  {id:'task2',title:'Task 2 · Quantification',audience:'Group',due:'2026-11-18T23:59:00+01:00',date:'18 November',time:'23:59',url:topic(1251173),source:topic(1251002),description:'Quantify impacts and discuss the balance between the three sustainability pillars.',checklist:['Evaluate environmental, economic and social aspects; discuss trade-offs.','Where relevant and possible, calculate the carbon footprint of energy consumption or another relevant impact measure.','Put results in perspective using comparable processes or consumables; compare production and use where relevant.','One person submits for the whole group in FeedbackFruits.',contribution,'Attach Task 1 as an annex.','Default maximum: 9,600 characters (about 4 pages), excluding bibliography and tables; case-specific instructions take precedence.',declaration]},
  {id:'peer2',title:'Task 2 · Give peer feedback',audience:'Individual',due:'2026-11-25T23:59:00+01:00',date:'25 November',time:'23:59',url:topic(1251173),source:topic(1251003),description:'Each student reviews two other groups and addresses every criterion.',checklist:['Review both assigned group submissions individually in FeedbackFruits.','Address every assessment criterion for both submissions.','AI use in peer feedback is not allowed.','As a group, consider received feedback for revisions.']},
  {id:'task3',title:'Task 3 · Assessment & outlook',audience:'Group',due:'2026-12-13T23:59:00+01:00',date:'13 December',time:'23:59',url:topic(1251188),source:topic(1251004),description:'Bring the project together: absolute sustainability, systemic effects, trade-offs and uncertainty.',checklist:['Assess your share of safe operating space and the global significance of your case.','Discuss a systemic perspective, circular economy opportunities and trade-offs between sustainability dimensions.','Integrate Tasks 1 and 2 into a multidimensional assessment; conclude and assess uncertainties.','One person submits for the whole group in the Microfabrication Task 3 assignment tool.',contribution,'Attach both Task 1 and Task 2 as annexes.','Default maximum: 9,600 characters (about 4 pages), excluding bibliography and tables; case-specific instructions take precedence.',declaration]},
  {id:'exam',title:'Multiple-choice exam',audience:'Individual',dateOnly:'2026-12-19',date:'19 December',time:'Time & room to be announced',url:course.examSource,source:course.catalogue,description:'60% of the final assessment. At least 50% correct answers are required to pass the quiz.',checklist:['Complete Task 1 and Task 2 submissions AND individual peer feedback to qualify for the exam.','Two-hour written multiple-choice exam; all aids allowed without internet access.','Confirm your exam registration and check DTU for the announced time and room.','Prepare materials locally: this online hub will not be available without internet.']},
];
const rows = [
  ['2026-08-31','2026-09-06','4 September','Problems, relevance & obligations',1250722,1250773,
    [
      ['Sustainability is a constraint on engineering decisions','A lower footprint is useful, but planetary thresholds ask whether the total activity remains within environmental limits. Keep the scale of the system visible when making a sustainability claim.'],
      ['Assess all three pillars','Environmental improvements can create economic or social trade-offs. For microfabrication, cheap or reliable chips alone do not establish sustainability; resource use and impacts also belong in the problem definition.'],
      ['Commitments influence what counts as progress','Global commitments and the EU taxonomy provide context for engineering choices. Distinguish an evidence-based assessment from an unsupported green claim.'],
    ],
    ['Write a five-line case motivation','Use your group’s chosen microfabrication topic. Name the function, one environmental concern, one economic concern, one social concern and the decision your assessment should inform.','A concise problem motivation you can reuse when discussing Task 1.','Check that all three pillars appear and that the decision is more specific than “is this sustainable?”.'],
    'Agree on a group and a manageable microfabrication topic. Group enrolment is due in week 2.',
  ],
  ['2026-09-07','2026-09-13','11 September','Assessment framework & functional unit',1250713,1250760,
    [
      ['Compare the same service','The functional unit quantifies what the system delivers. Comparing one chip with one different chip is misleading if their performance, lifetime or service differs. Define the function before choosing quantities.'],
      ['Boundaries determine what you leave out','Map raw materials, manufacturing, use and end of life. State exclusions so that the comparison remains interpretable; a manufacturing-only result is not automatically a whole-life result.'],
      ['Use a tiered assessment','Start with screening and increase detail where it changes the decision. Data requirements grow with assessment depth, so prioritise likely hotspots instead of collecting every possible measurement.'],
    ],
    ['Sketch the system on one page','Define one measurable functional unit for your actual project. Draw the main life-cycle stages, mark the boundary and list three important assumptions.','A functional unit and simple process-flow diagram for Task 1.','Could another group reproduce the comparison from your function, quantity, lifetime and boundary?'],
    'Finish group enrolment by Friday. Use the functional unit and flow diagram as the foundation for Task 1.',
  ],
  ['2026-09-14','2026-09-20','18 September','Case study · Problem formulation',1250710,1251165,
    [
      ['Make the assessment answer one question','Microfabrication offers several possible projects: a manufacturer, DTU’s facility, a specific process or high-purity chemicals. Use your group’s selected topic and keep the assessment question narrow enough to investigate.'],
      ['Missing data is part of the case','This is an investigative project rather than a textbook dataset. Record proxies, gaps and assumptions as you go; an apparently precise number is weak evidence if its inputs are poorly supported.'],
      ['Task 1 is the assessment contract','The problem statement, functional unit and boundaries set what later calculations mean. A clear scope now reduces rework when you quantify impacts in Task 2.'],
    ],
    ['Stress-test your problem statement','Spend 30 minutes reviewing your Task 1 scope against the case brief. For each pillar, identify a motivation; then note one data source and one uncertainty for the main impact you plan to calculate.','A short list of scope corrections and data questions for your group.','Your scope identifies the object, quantified function, boundary and assumptions without claiming conclusions before calculations.'],
    'Use the case session to clarify scope. Task 1 is due on 30 September; the session itself is not listed as a graded submission.',
  ],
  ['2026-09-21','2026-09-27','25 September','Carbon footprint & environmental indicators',1250714,1250736,
    [
      ['An inventory becomes an impact through factors','Multiply activity quantities by compatible impact factors and sum over the boundary. Check units carefully: kWh × kg CO₂e/kWh gives kg CO₂e, whereas a factor in grams needs conversion.'],
      ['The comparison includes more than operation','The mobility exercise compares production and use, illustrating why a cleaner operating phase can coexist with production burdens. Apply the same boundary discipline to chip manufacture and chip use.'],
      ['Carbon is one indicator','A climate result does not cover every environmental effect. Use carbon to find important contributions, while keeping other relevant impacts visible in the case assessment.'],
      ['Use the current spreadsheet','Some process numbers differ from the videos. Match the activity name to the process in the current workbook, and use the supplied solutions to check your work.'],
    ],
    ['Complete one mobility comparison','Open the carbon-footprint mobility workbook and Tool instructions 1–3. Fill the highlighted inputs for the gasoline/electric comparison, inspect the largest contribution and compare against the solution.','One checked comparison, with a sentence explaining its main driver.','Units, selected process names and production/use boundaries match; investigate a mismatch before changing assumptions.'],
    'Finalise the Task 1 scope before the 30 September deadline. The carbon exercise and self-assessment are explicitly practice, not assessed results.',
  ],
  ['2026-09-28','2026-10-04','2 October','Health dimensions',1250716,1250737,
    [
      ['Health effects need their own assessment','Climate emissions alone do not describe human health burdens. The module connects inventory-based health impacts, disease burdens and effects on users. Keep the mechanism and indicator clear.'],
      ['Include harms and benefits consistently','The mobility exercise includes health effects of physical activity as well as burdens. An assessment can omit a major effect if it looks only at emissions from a process.'],
      ['One inventory supports several indicators','The mobility workbook contains hidden health and ecosystem columns. Expanding them reuses the inventory; it does not remove uncertainty in activity data or characterisation factors.'],
    ],
    ['Explain one health trade-off','Use Tool instructions 4 and the health mobility workbook. Expand the impact columns, compare cycling with one vehicle option and write down the role of physical activity alongside production/use impacts.','A three-sentence explanation of why the health comparison can differ from a carbon-only comparison.','Keep the indicator and units explicit and compare with the solutions released through the self-assessment.'],
    'Submit Task 1 by Wednesday 30 September. Each student must also complete peer feedback by 7 October.',
  ],
  ['2026-10-05','2026-10-11','9 October','Economic dimensions',1250723,1250770,
    [
      ['Purchase price is not life-cycle cost','Life Cycle Costing includes costs over the chosen lifetime and boundary. An expensive efficient option can have lower total cost; record usage and price assumptions before comparing.'],
      ['Sensitivity reveals decision drivers','Changing electricity prices or lifetime can change which option is cheapest. Test influential assumptions rather than treating a single price scenario as a permanent answer.'],
      ['MCDA makes trade-offs explicit','Multi-Criteria Decision Assessment and AHP combine criteria using preferences or weights. The ranking depends on those choices, so explain them and check how robust the conclusion is.'],
      ['Cost is one pillar, not the whole conclusion','A low-cost process can still have environmental or social burdens. For microfabrication, place cost results alongside the other dimensions instead of replacing them.'],
    ],
    ['Test one cost assumption','Open the LCC mobility exercise, fill the missing cost inputs and compare with the solution. Change one influential price or lifetime assumption and note whether the ranking changes.','A baseline and alternative scenario with one sentence on robustness.','Use the same functional unit and lifetime, and distinguish recurring costs from purchase costs.'],
    'Complete your individual Task 1 peer feedback by Wednesday 7 October. Then start the data inventory for Task 2.',
  ],
  ['2026-10-19','2026-10-25','23 October','Planetary boundaries & absolute sustainability',1250717,1250746,
    [
      ['Better does not necessarily mean sustainable','Relative assessment asks which option has lower impact. Absolute assessment compares impact with an allocated share of environmental capacity; both options can improve while still exceeding that share.'],
      ['Allocation is a consequential choice','Translating a planetary boundary to a product or activity requires a sharing principle. Human needs, population or other allocation choices imply different ethical assumptions and can change the result.'],
      ['Compare like units and scales','A footprint and its allocated boundary must describe compatible quantities, time periods and indicators. The ratio is only useful once those choices are explicit.'],
    ],
    ['Interpret one absolute-assessment result','Use Tool instructions 7 and the mobility absolute-sustainability exercise. Identify the impact, allocated boundary and allocation rule for one option; explain what changes if the allowed share changes.','A short distinction between “lower impact” and “within the allocated boundary”.','Can you identify the numerator, denominator, units and ethical assumption behind the comparison?'],
    'Resume Task 2 after the autumn break. Record the allocation assumptions you may need for the final Microfabrication assessment.',
  ],
  ['2026-10-26','2026-11-01','30 October','Resource management, scarcity & criticality',1250715,1250742,
    [
      ['Renewable resources can still be overused','Sustainable extraction depends on regeneration, not merely on whether a resource is labelled renewable. Fisheries illustrate how management decisions affect future availability.'],
      ['Extraction has wider impacts','A sustainable yield does not guarantee a low biodiversity or environmental footprint. Assess the wider consequences of the extraction strategy as well as the quantity harvested.'],
      ['Criticality is broader than physical scarcity','The criticality reading considers resource risks and vulnerability. For microfabrication, a small quantity of a hard-to-substitute material may deserve attention alongside high-volume energy or water inputs.'],
      ['Shared resources require governance','The commons problem helps explain why individually rational extraction can undermine collective outcomes. Management rules and incentives matter to the sustainability conclusion.'],
    ],
    ['Screen three resources in your project','List three relevant inputs such as electricity, water or a process material. For each, identify a supply or regeneration concern, a wider environmental concern and the quality of your evidence.','A three-row resource-risk screen that can inform the case discussion.','Avoid equating “rare”, “high carbon” and “critical”; explain the particular risk for each input.'],
    'Gather and document Task 2 inputs. Prepare questions about uncertain resource data for the week-9 case session.',
  ],
  ['2026-11-02','2026-11-08','6 November','Case study · Applying methods',1250711,1251166,
    [
      ['Trace every important calculation','Task 2 needs a transparent connection from activity data to an impact measure. Label sources, units, assumptions and conversions so the group can explain the result.'],
      ['Put the number in perspective','Compare with a relevant process or consumable using a defensible basis. A large absolute figure and a large impact per functional unit answer different questions.'],
      ['Quantification still needs all three pillars','The brief asks for environmental, economic and social aspects and their balance. Discuss relevant limitations when data are insufficient rather than inventing precise indicators.'],
      ['Use the case session to resolve blockers','The Microfabrication agenda asks for a three-slide, roughly three-minute group pitch on progress and questions. It is preparation for feedback, not a separately listed graded deadline.'],
    ],
    ['Audit one key calculation','Take your project’s main impact calculation. Check dimensions, trace each input to a source and try one lower/higher plausible value for the weakest input.','An auditable baseline, a sensitivity result and one precise question for the teaching team.','A groupmate can reproduce the result and explain why the uncertainty matters.'],
    'Class preparation: bring three slides on project progress and questions on 6 November. Task 2 is due on 18 November.',
  ],
  ['2026-11-09','2026-11-15','13 November','Energy systems & decarbonisation',1250718,1250755,
    [
      ['Electricity impact depends on the mix','Weight each technology’s life-cycle emissions by its share of production. The mix’s g CO₂e/kWh then combines with electricity demand; shares must sum to a coherent total.'],
      ['Low operating emissions do not mean zero life-cycle impact','Electricity technologies have construction and supply-chain impacts too. Use life-cycle factors consistently rather than comparing one technology’s operation with another’s full life cycle.'],
      ['Intensity and total emissions are different','A lower-carbon mix can still produce substantial emissions when demand is high. The module compares mix scenarios with climate-related boundaries, making scale central to the conclusion.'],
      ['Energy assumptions matter for microfabrication','An energy-intensive process can be sensitive to location and supply mix. Separate an actual sourcing scenario from a hypothetical decarbonisation scenario.'],
    ],
    ['Change one electricity-mix scenario','Open Planetary CO2 boundary – Electricity Technology Mix. Inspect the baseline and test one change in technology shares while keeping the shares consistent; compare intensity and total emissions.','Two scenarios and a sentence on the role of demand versus technology mix.','Check g versus kg, kWh versus larger energy units and whether the changed scenario is an assumption or observed data.'],
    'Finish Task 2 calculations and annexes before 18 November. Keep the baseline and sensitivity assumptions visible.',
  ],
  ['2026-11-16','2026-11-22','20 November','Circular economy',1250720,1250774,
    [
      ['Circularity is a strategy, not an impact result','Extending use, recovery or recycling can change resource flows. Whether a strategy improves sustainability requires quantifying the resulting changes and trade-offs.'],
      ['Specify what changes in the system','Identify the material, process or service affected, the recovery rate and any extra energy or processing. A circularity proposal without those assumptions cannot support a defensible comparison.'],
      ['Readiness affects implementation','The module introduces ready2LOOP and the Circularity Strategy Scanner. Technical feasibility, organisation and other readiness conditions matter when turning a proposed strategy into practice.'],
    ],
    ['Screen one circular strategy','Choose one relevant option for your actual microfabrication project: for example longer use, recovery of a process material or reuse. State the necessary assumptions, a potential benefit and an added burden.','A short strategy proposal with a condition under which it would fail to improve sustainability.','Connect the strategy to measurable system changes rather than assuming that recycling is automatically beneficial.'],
    'Submit Task 2 by Wednesday 18 November. Individual peer feedback is due on 25 November.',
  ],
  ['2026-11-23','2026-11-29','27 November','Sustainability transitions',1250721,1250777,
    [
      ['Transitions involve connected systems','Changing one technology can alter demand, infrastructure and behaviour. Use a systemic perspective to identify interactions that a narrow product comparison may miss.'],
      ['Feedbacks and delays affect outcomes','System-dynamics exercises explore how interventions work over time. A promising immediate change can have different longer-term consequences when reinforcing or balancing effects are included.'],
      ['Interpret dimensions together','The assigned assessment-interpretation reading supports presenting combined results. Keep conflicting indicators and uncertainty visible instead of hiding them in one unsupported sustainability score.'],
    ],
    ['Map a small transition pathway','For one proposed improvement in your project, draw a causal chain with one feedback loop or delay. Add a three-column table of environmental, economic and social effects, including uncertainties.','One diagram and a balanced interpretation to help structure Task 3.','Explain the direction of each connection and distinguish established evidence from a hypothesis.'],
    'Complete individual Task 2 peer feedback by Wednesday 25 November. Use received feedback to identify revisions for Task 3.',
  ],
  ['2026-11-30','2026-12-06','4 December','Case study · Integrated assessment',1250712,1251170,
    [
      ['Integrate rather than repeat','Task 3 combines prior scope and calculations into a multidimensional conclusion. Use Tasks 1 and 2 as foundations, then explain what they jointly establish about sustainability.'],
      ['Evaluate safe operating space','Discuss the case’s allocated share and global significance where supportable. Make the allocation and scale assumptions explicit; uncertain data should limit the strength of the conclusion.'],
      ['Explain systemic trade-offs','Consider circular-economy opportunities and interactions among the three pillars. Show where a proposed improvement shifts burdens or depends on wider system conditions.'],
      ['A good conclusion states its limits','The case criteria emphasise critical evaluation, a systemic perspective, uncertainty and integration. Explain what remains unknown and whether it could change the recommendation.'],
    ],
    ['Review the conclusion against four criteria','Read your draft conclusion against critical sustainability evaluation, systemic perspective, uncertainty and integration of Tasks 1–2. Identify one unsupported claim and one important limitation to fix.','A short revision list and focused questions for the week-13 teaching team.','The conclusion answers the original question and does not claim more certainty than the input data support.'],
    'Prepare questions for the 4 December case session. Task 3 is due after teaching ends, on 13 December; the exam follows on 19 December.',
  ],
];
export const weeks = rows.map((r,i) => ({
  number:i+1,start:r[0],end:r[1],classDate:r[2],title:r[3],module:r[4],source:topic(r[5]),url:unit(r[4]),
  takeaways:r[6].map(([title,text])=>({title,text})),practice:{title:exercises[i+1].title||r[7][0],steps:exercises[i+1].prompt,result:r[7][2],check:r[7][3],minutes:'30–60 min'},project:r[8],
}));
